grafana:
  service:
    type: NodePort
    nodePort: 30563
  adminUser: admin
  adminPassword: admin
  defaultDashboardsTimezone: browser

prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s

alertmanager:
  service:
    type: NodePort
    nodePort: 30903
  alertmanagerSpec:
    retention: 120h

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
